; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -unroll-runtime -unroll-count=2 -passes=loop-unroll | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nounwind
define dso_local void @test_loop_unroll_01(ptr nocapture %_pA) local_unnamed_addr #0 {
; CHECK-LABEL: @test_loop_unroll_01(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META2:![0-9]+]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr [[_PA:%.*]], ptr [[TMP0]], ptr null, ptr undef, i32 0, metadata [[META2]]), !tbaa [[TBAA5:![0-9]+]], !noalias !2
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[I_06:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_1:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[_PA]], i32 [[I_06]]
; CHECK-NEXT:    store i32 [[I_06]], ptr [[ARRAYIDX]], ptr_provenance ptr [[TMP1]], align 4, !tbaa [[TBAA9:![0-9]+]], !noalias !2
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i32 [[I_06]], 1
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[_PA]], i32 [[INC]]
; CHECK-NEXT:    store i32 [[INC]], ptr [[ARRAYIDX_1]], ptr_provenance ptr [[TMP1]], align 4, !tbaa [[TBAA9]], !noalias !2
; CHECK-NEXT:    [[INC_1]] = add nuw nsw i32 [[I_06]], 2
; CHECK-NEXT:    [[EXITCOND_1:%.*]] = icmp eq i32 [[INC_1]], 4
; CHECK-NEXT:    br i1 [[EXITCOND_1]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
;
entry:
  %0 = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata !2)
  %1 = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr %_pA, ptr %0, ptr null, ptr undef, i32 0, metadata !2), !tbaa !5, !noalias !2
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %i.06 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %arrayidx = getelementptr inbounds i32, ptr %_pA, i32 %i.06
  store i32 %i.06, ptr %arrayidx, ptr_provenance ptr %1, align 4, !tbaa !9, !noalias !2
  %inc = add nuw nsw i32 %i.06, 1
  %exitcond = icmp eq i32 %inc, 4
  br i1 %exitcond, label %for.cond.cleanup, label %for.body
}

; Function Attrs: argmemonly nounwind
declare ptr @llvm.noalias.decl.p0.p0.i32(ptr, i32, metadata) #1

; Function Attrs: nounwind
define dso_local void @test_loop_unroll_02(ptr nocapture %_pA) local_unnamed_addr #0 {
; CHECK-LABEL: @test_loop_unroll_02(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[I_06:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_1:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META13:![0-9]+]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr [[_PA:%.*]], ptr [[TMP0]], ptr null, ptr undef, i32 0, metadata [[META13]]), !tbaa [[TBAA5]], !noalias !13
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[_PA]], i32 [[I_06]]
; CHECK-NEXT:    store i32 [[I_06]], ptr [[ARRAYIDX]], ptr_provenance ptr [[TMP1]], align 4, !tbaa [[TBAA9]], !noalias !13
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i32 [[I_06]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META16:![0-9]+]])
; CHECK-NEXT:    [[TMP3:%.*]] = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr [[_PA]], ptr [[TMP2]], ptr null, ptr undef, i32 0, metadata [[META16]]), !tbaa [[TBAA5]], !noalias !16
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[_PA]], i32 [[INC]]
; CHECK-NEXT:    store i32 [[INC]], ptr [[ARRAYIDX_1]], ptr_provenance ptr [[TMP3]], align 4, !tbaa [[TBAA9]], !noalias !16
; CHECK-NEXT:    [[INC_1]] = add nuw nsw i32 [[I_06]], 2
; CHECK-NEXT:    [[EXITCOND_1:%.*]] = icmp eq i32 [[INC_1]], 4
; CHECK-NEXT:    br i1 [[EXITCOND_1]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP18:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %i.06 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %0 = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata !11)
  %1 = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr %_pA, ptr %0, ptr null, ptr undef, i32 0, metadata !11), !tbaa !5, !noalias !11
  %arrayidx = getelementptr inbounds i32, ptr %_pA, i32 %i.06
  store i32 %i.06, ptr %arrayidx, ptr_provenance ptr %1, align 4, !tbaa !9, !noalias !11
  %inc = add nuw nsw i32 %i.06, 1
  %exitcond = icmp eq i32 %inc, 4
  br i1 %exitcond, label %for.cond.cleanup, label %for.body
}

; Function Attrs: nounwind
define dso_local void @test_loop_unroll_03(ptr nocapture %_pA, i1 %c) local_unnamed_addr #0 {
; CHECK-LABEL: @test_loop_unroll_03(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[I_06:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_1:%.*]], [[FOR_BODY1_1:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META19:![0-9]+]])
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[_PA:%.*]], i32 [[I_06]]
; CHECK-NEXT:    br i1 [[C:%.*]], label [[ALT_EXIT:%.*]], label [[FOR_BODY1:%.*]]
; CHECK:       for.body1:
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA9]], !noalias !19
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i32 [[I_06]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META22:![0-9]+]])
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[_PA]], i32 [[INC]]
; CHECK-NEXT:    br i1 [[C]], label [[ALT_EXIT]], label [[FOR_BODY1_1]]
; CHECK:       for.body1.1:
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX_1]], align 4, !tbaa [[TBAA9]], !noalias !22
; CHECK-NEXT:    [[INC_1]] = add nuw nsw i32 [[I_06]], 2
; CHECK-NEXT:    [[EXITCOND_1:%.*]] = icmp eq i32 [[INC_1]], 4
; CHECK-NEXT:    br i1 [[EXITCOND_1]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP24:![0-9]+]]
; CHECK:       alt.exit:
; CHECK-NEXT:    [[I_06_LCSSA:%.*]] = phi i32 [ [[I_06]], [[FOR_BODY]] ], [ [[INC]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[TMP0]], [[FOR_BODY]] ], [ [[TMP1]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[ARRAYIDX_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_BODY]] ], [ [[ARRAYIDX_1]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata [[META25:![0-9]+]])
; CHECK-NEXT:    [[S:%.*]] = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr [[_PA]], ptr [[TMP2]], ptr null, ptr undef, i32 0, metadata [[META25]]), !tbaa [[TBAA5]], !noalias !25
; CHECK-NEXT:    store i32 [[I_06_LCSSA]], ptr [[ARRAYIDX_LCSSA]], ptr_provenance ptr [[S]], align 4, !tbaa [[TBAA9]], !noalias !25
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %i.06 = phi i32 [ 0, %entry ], [ %inc, %for.body1 ]
  %0 = tail call ptr @llvm.noalias.decl.p0.p0.i32(ptr null, i32 0, metadata !14)
  %arrayidx = getelementptr inbounds i32, ptr %_pA, i32 %i.06
  br i1 %c, label %alt.exit, label %for.body1

for.body1:
  store i32 1, ptr %arrayidx, align 4, !tbaa !9, !noalias !14
  %inc = add nuw nsw i32 %i.06, 1
  %exitcond = icmp eq i32 %inc, 4
  br i1 %exitcond, label %for.cond.cleanup, label %for.body

alt.exit:
  %s = tail call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr %_pA, ptr %0, ptr null, ptr undef, i32 0, metadata !14), !tbaa !5, !noalias !14
  store i32 %i.06, ptr %arrayidx, ptr_provenance ptr %s, align 4, !tbaa !9, !noalias !14
  ret void
}

; Function Attrs: nounwind readnone speculatable
declare ptr @llvm.provenance.noalias.p0.p0.p0.p0.i32(ptr, ptr, ptr, ptr, i32, metadata) #2

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { argmemonly nounwind }
attributes #2 = { nounwind readnone speculatable }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang"}
!2 = !{!3}
!3 = distinct !{!3, !4, !"test_loop_unroll_01: pA"}
!4 = distinct !{!4, !"test_loop_unroll_01"}
!5 = !{!6, !6, i64 0, i64 4}
!6 = !{!7, i64 4, !"any pointer"}
!7 = !{!8, i64 1, !"omnipotent char"}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0, i64 4}
!10 = !{!7, i64 4, !"int"}
!11 = !{!12}
!12 = distinct !{!12, !13, !"test_loop_unroll_02: pA"}
!13 = distinct !{!13, !"test_loop_unroll_02"}
!14 = !{!15}
!15 = distinct !{!15, !16, !"test_loop_unroll_03: pA"}
!16 = distinct !{!16, !"test_loop_unroll_03"}

; CHECK: !0 = !{i32 1, !"wchar_size", i32 4}
; CHECK: !1 = !{!"clang"}
; CHECK: !3 = distinct !{!3, !4, !"test_loop_unroll_01: pA"}
; CHECK: !4 = distinct !{!4, !"test_loop_unroll_01"}
; CHECK: !5 = !{!6, !6, i64 0, i64 4}
; CHECK: !6 = !{!7, i64 4, !"any pointer"}
; CHECK: !7 = !{!8, i64 1, !"omnipotent char"}
; CHECK: !8 = !{!"Simple C/C++ TBAA"}
; CHECK: !9 = !{!10, !10, i64 0, i64 4}
; CHECK: !10 = !{!7, i64 4, !"int"}
; CHECK: !11 = distinct !{!11, !12}
; CHECK: !12 = !{!"llvm.loop.unroll.disable"}
; CHECK: !14 = distinct !{!14, !15, !"test_loop_unroll_02: pA:It0"}
; CHECK: !15 = distinct !{!15, !"test_loop_unroll_02"}
; CHECK: !17 = distinct !{!17, !15, !"test_loop_unroll_02: pA:It1"}
; CHECK: !18 = distinct !{!18, !12}
; CHECK: !20 = distinct !{!20, !21, !"test_loop_unroll_03: pA:It0"}
; CHECK: !21 = distinct !{!21, !"test_loop_unroll_03"}
; CHECK: !23 = distinct !{!23, !21, !"test_loop_unroll_03: pA:It1"}
; CHECK: !26 = distinct !{!26, !21, !"test_loop_unroll_03: pA"}
