; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=sroa -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.wobble.63 = type <{ %struct.blam.64, i32, [4 x i8] }>
%struct.blam.64 = type { i64 }

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #0

define hidden void @test01(i1 %a0) local_unnamed_addr align 32 {
; CHECK-LABEL: @test01(
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br i1 [[A0:%.*]], label [[BB2:%.*]], label [[BB3:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    br label [[BB3]]
; CHECK:       bb3:
; CHECK-NEXT:    [[TMP26167:%.*]] = phi ptr [ null, [[BB2]] ], [ undef, [[BB1]] ]
; CHECK-NEXT:    ret void
;
bb0:
  %tmp73 = alloca %struct.wobble.63, align 8
  call void @llvm.lifetime.start.p0(i64 16, ptr %tmp73)
  br label %bb1

bb1:                                          ; preds = %bb25700
  br i1 %a0, label %bb2, label %bb3

bb2:                                          ; preds = %bb26124
  %tmp26144 = call ptr @llvm.provenance.noalias.p0.p0.p0.p0.i64(ptr nonnull %tmp73, ptr undef, ptr null, ptr undef, i64 0, metadata !1)
  %tmp26145 = getelementptr %struct.wobble.63, ptr %tmp26144, i64 0, i32 0, i32 0
  br label %bb3

bb3:                                          ; preds = %bb26143, %bb26131
  %tmp26167 = phi i64* [ %tmp26145, %bb2 ], [ undef, %bb1 ]
  ret void
}

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare ptr @llvm.provenance.noalias.p0.p0.p0.p0.i64(ptr, ptr, ptr, ptr, i64, metadata) #1

attributes #0 = { argmemonly nofree nosync nounwind willreturn }
attributes #1 = { nofree nosync nounwind readnone speculatable willreturn }

!llvm.ident = !{!0 }

!0 = !{!"clang"}
!1 = !{!2}
!2 = distinct !{!2, !3, !"test02: argument 0"}
!3 = distinct !{!3, !"test01"}
