// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs --replace-value-regex "__omp_offloading_[0-9a-z]+_[0-9a-z]+" "reduction_size[.].+[.]" "pl_cond[.].+[.|,]" --prefix-filecheck-ir-name _
// RUN: %clang_cc1 -DCK1 -verify -fopenmp -x c++ -triple powerpc64le-unknown-unknown -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-cuda-mode -emit-llvm-bc %s -o %t-ppc-host.bc
// RUN: %clang_cc1 -DCK1 -verify -fopenmp -x c++ -triple nvptx64-unknown-unknown -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-cuda-mode -emit-llvm %s -fopenmp-is-target-device -fopenmp-host-ir-file-path %t-ppc-host.bc -o - -debug-info-kind=limited | FileCheck %s --check-prefix=CHECK1
// expected-no-diagnostics

int main() {
  /* int(*b)[a]; */
  /* int *(**c)[a]; */
  bool bb;
  int a;
  int b[10][10];
  int c[10][10][10];
#pragma omp target parallel for firstprivate(a, b) map(tofrom          \
                                                       : c) map(tofrom \
                                                                : bb) if (a)
  for (int i = 0; i < 10; ++i) {
    int &f = c[1][1][1];
    int &g = a;
    int &h = b[1][1];
    int d = 15;
    a = 5;
    b[0][a] = 10;
    c[0][0][a] = 11;
    b[0][a] = c[0][0][a];
    bb |= b[0][a];
  }
#pragma omp target parallel for firstprivate(a) map(tofrom         \
                                                    : c, b) map(to \
                                                                : bb)
  for (int i = 0; i < 10; ++i) {
    int &f = c[1][1][1];
    int &g = a;
    int &h = b[1][1];
    int d = 15;
    a = 5;
    b[0][a] = 10;
    c[0][0][a] = 11;
    b[0][a] = c[0][0][a];
    d = bb;
  }
#pragma omp target parallel for map(tofrom              \
                                    : a, c, b) map(from \
                                                   : bb)
  for (int i = 0; i < 10; ++i) {
    int &f = c[1][1][1];
    int &g = a;
    int &h = b[1][1];
    int d = 15;
    a = 5;
    b[0][a] = 10;
    c[0][0][a] = 11;
    b[0][a] = c[0][0][a];
    bb = b[0][a];
  }
  return 0;
}
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug__
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], i32 noundef [[A:%.*]], ptr noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]], i1 noundef zeroext [[DOTCAPTURE_EXPR_:%.*]]) #[[ATTR0:[0-9]+]] !dbg [[DBG10:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[DOTCAPTURE_EXPR__ADDR:%.*]] = alloca i8, align 1
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_CASTED:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[CAPTURED_VARS_ADDRS:%.*]] = alloca [4 x ptr], align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META34:![0-9]+]], !DIExpression(), [[META35:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META36:![0-9]+]], !DIExpression(), [[META37:![0-9]+]])
// CHECK1-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META38:![0-9]+]], !DIExpression(), [[META39:![0-9]+]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META40:![0-9]+]], !DIExpression(), [[META41:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META42:![0-9]+]], !DIExpression(), [[META43:![0-9]+]])
// CHECK1-NEXT:    [[STOREDV:%.*]] = zext i1 [[DOTCAPTURE_EXPR_]] to i8
// CHECK1-NEXT:    store i8 [[STOREDV]], ptr [[DOTCAPTURE_EXPR__ADDR]], align 1
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTCAPTURE_EXPR__ADDR]], [[META44:![0-9]+]], !DIExpression(), [[META45:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG46:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META31:![0-9]+]]), !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG46]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG46]], !nonnull [[META30:![0-9]+]], !align [[META47:![0-9]+]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP4]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META31]]), !dbg [[DBG46]]
// CHECK1-NEXT:    store ptr [[TMP5]], ptr [[_TMP1]], align 8, !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG46]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP8:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP7]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META31]]), !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP9:%.*]] = addrspacecast ptr addrspace(1) [[TMP8]] to ptr, !dbg [[DBG46]]
// CHECK1-NEXT:    store ptr [[TMP9]], ptr [[_TMP2]], align 8, !dbg [[DBG46]]
// CHECK1-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG46]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP11:%.*]] = call i32 @__kmpc_target_init(ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_kernel_environment, ptr [[DYN_PTR]]), !dbg [[DBG46]]
// CHECK1-NEXT:    [[EXEC_USER_CODE:%.*]] = icmp eq i32 [[TMP11]], -1, !dbg [[DBG46]]
// CHECK1-NEXT:    br i1 [[EXEC_USER_CODE]], label [[USER_CODE_ENTRY:%.*]], label [[WORKER_EXIT:%.*]], !dbg [[DBG46]]
// CHECK1:       user_code.entry:
// CHECK1-NEXT:    [[TMP12:%.*]] = call i32 @__kmpc_global_thread_num(ptr @[[GLOB6:[0-9]+]]), !dbg [[DBG48:![0-9]+]]
// CHECK1-NEXT:    [[TMP13:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG50:![0-9]+]]
// CHECK1-NEXT:    store i32 [[TMP13]], ptr [[A_CASTED]], align 4, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP14:%.*]] = load i64, ptr [[A_CASTED]], align 8, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP15:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 0, !dbg [[DBG50]]
// CHECK1-NEXT:    store ptr [[TMP3]], ptr [[TMP15]], align 8, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 1, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP17:%.*]] = inttoptr i64 [[TMP14]] to ptr, !dbg [[DBG50]]
// CHECK1-NEXT:    store ptr [[TMP17]], ptr [[TMP16]], align 8, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP18:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 2, !dbg [[DBG50]]
// CHECK1-NEXT:    store ptr [[TMP6]], ptr [[TMP18]], align 8, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 3, !dbg [[DBG50]]
// CHECK1-NEXT:    store ptr [[TMP10]], ptr [[TMP19]], align 8, !dbg [[DBG50]]
// CHECK1-NEXT:    [[TMP20:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR__ADDR]], align 1, !dbg [[DBG51:![0-9]+]]
// CHECK1-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP20]] to i1, !dbg [[DBG51]]
// CHECK1-NEXT:    [[TMP21:%.*]] = zext i1 [[LOADEDV]] to i32, !dbg [[DBG50]]
// CHECK1-NEXT:    call void @__kmpc_parallel_51(ptr @[[GLOB6]], i32 [[TMP12]], i32 [[TMP21]], i32 -1, i32 -1, ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug___omp_outlined, ptr null, ptr [[CAPTURED_VARS_ADDRS]], i64 4), !dbg [[DBG50]]
// CHECK1-NEXT:    call void @__kmpc_target_deinit(), !dbg [[DBG52:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG53:![0-9]+]]
// CHECK1:       worker.exit:
// CHECK1-NEXT:    ret void, !dbg [[DBG46]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], i64 noundef [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]], i64 noundef [[DOTCAPTURE_EXPR_:%.*]]) #[[ATTR1:[0-9]+]] !dbg [[DBG54:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTCAPTURE_EXPR__ADDR:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META64:![0-9]+]], !DIExpression(), [[META65:![0-9]+]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META66:![0-9]+]], !DIExpression(), [[META65]])
// CHECK1-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META67:![0-9]+]], !DIExpression(), [[META65]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META68:![0-9]+]], !DIExpression(), [[META65]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META69:![0-9]+]], !DIExpression(), [[META65]])
// CHECK1-NEXT:    store i64 [[DOTCAPTURE_EXPR_]], ptr [[DOTCAPTURE_EXPR__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTCAPTURE_EXPR__ADDR]], [[META70:![0-9]+]], !DIExpression(), [[META65]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG71:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG71]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG71]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DYN_PTR_ADDR]], align 8, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP4:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP3]], ptr null, ptr [[DYN_PTR_ADDR]], i64 0, metadata [[META61:![0-9]+]]), !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP9:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR__ADDR]], align 1, !dbg [[DBG71]]
// CHECK1-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP9]] to i1, !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr [[TMP5]] to ptr addrspace(1), !dbg [[DBG71]]
// CHECK1-NEXT:    [[TMP11:%.*]] = addrspacecast ptr [[TMP8]] to ptr addrspace(1), !dbg [[DBG71]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug__(ptr [[TMP4]], ptr addrspace(1) [[TMP10]], i32 [[TMP6]], ptr [[TMP7]], ptr addrspace(1) [[TMP11]], i1 [[LOADEDV]]) #[[ATTR4:[0-9]+]], !dbg [[DBG71]]
// CHECK1-NEXT:    ret void, !dbg [[DBG71]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug___omp_outlined_debug__
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], i32 noundef [[A:%.*]], ptr noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG72:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTOMP_IV:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[_TMP3:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_LB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_UB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[B4:%.*]] = alloca [10 x [10 x i32]], align 4
// CHECK1-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[F:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[G:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[H:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META82:![0-9]+]], !DIExpression(), [[META83:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META84:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META85:![0-9]+]], !DIExpression(), [[META86:![0-9]+]])
// CHECK1-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META87:![0-9]+]], !DIExpression(), [[META88:![0-9]+]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META89:![0-9]+]], !DIExpression(), [[META90:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META91:![0-9]+]], !DIExpression(), [[META92:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG93:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META79:![0-9]+]]), !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG93]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG93]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP4]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META79]]), !dbg [[DBG93]]
// CHECK1-NEXT:    store ptr [[TMP5]], ptr [[_TMP1]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG93]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP8:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP7]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META79]]), !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP9:%.*]] = addrspacecast ptr addrspace(1) [[TMP8]] to ptr, !dbg [[DBG93]]
// CHECK1-NEXT:    store ptr [[TMP9]], ptr [[_TMP2]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG93]], !nonnull [[META30]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IV]], [[META94:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_LB]], [[META95:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG96:![0-9]+]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_UB]], [[META97:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    store i32 9, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_STRIDE]], [[META98:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    store i32 1, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IS_LAST]], [[META99:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_IS_LAST]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:      #dbg_declare(ptr [[B4]], [[META100:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[B4]], ptr align 4 [[TMP6]], i64 400, i1 false), !dbg [[DBG93]]
// CHECK1-NEXT:      #dbg_declare(ptr [[I]], [[META101:![0-9]+]], !DIExpression(), [[META83]])
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP12:%.*]] = load i32, ptr [[TMP11]], align 4, !dbg [[DBG93]]
// CHECK1-NEXT:    call void @__kmpc_for_static_init_4(ptr @[[GLOB3:[0-9]+]], i32 [[TMP12]], i32 33, ptr [[DOTOMP_IS_LAST]], ptr [[DOTOMP_LB]], ptr [[DOTOMP_UB]], ptr [[DOTOMP_STRIDE]], i32 1, i32 1), !dbg [[DBG102:![0-9]+]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND:%.*]], !dbg [[DBG93]]
// CHECK1:       omp.dispatch.cond:
// CHECK1-NEXT:    [[TMP13:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP13]], 9, !dbg [[DBG96]]
// CHECK1-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]], !dbg [[DBG96]]
// CHECK1:       cond.true:
// CHECK1-NEXT:    br label [[COND_END:%.*]], !dbg [[DBG96]]
// CHECK1:       cond.false:
// CHECK1-NEXT:    [[TMP14:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    br label [[COND_END]], !dbg [[DBG96]]
// CHECK1:       cond.end:
// CHECK1-NEXT:    [[COND:%.*]] = phi i32 [ 9, [[COND_TRUE]] ], [ [[TMP14]], [[COND_FALSE]] ], !dbg [[DBG96]]
// CHECK1-NEXT:    store i32 [[COND]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP15:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    store i32 [[TMP15]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP16:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP17:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[CMP5:%.*]] = icmp sle i32 [[TMP16]], [[TMP17]], !dbg [[DBG93]]
// CHECK1-NEXT:    br i1 [[CMP5]], label [[OMP_DISPATCH_BODY:%.*]], label [[OMP_DISPATCH_END:%.*]], !dbg [[DBG93]]
// CHECK1:       omp.dispatch.body:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND:%.*]], !dbg [[DBG93]]
// CHECK1:       omp.inner.for.cond:
// CHECK1-NEXT:    [[TMP18:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP19:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[CMP6:%.*]] = icmp sle i32 [[TMP18]], [[TMP19]], !dbg [[DBG93]]
// CHECK1-NEXT:    br i1 [[CMP6]], label [[OMP_INNER_FOR_BODY:%.*]], label [[OMP_INNER_FOR_END:%.*]], !dbg [[DBG93]]
// CHECK1:       omp.inner.for.body:
// CHECK1-NEXT:    [[TMP20:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP20]], 1, !dbg [[DBG103:![0-9]+]]
// CHECK1-NEXT:    [[ADD:%.*]] = add nsw i32 0, [[MUL]], !dbg [[DBG103]]
// CHECK1-NEXT:    store i32 [[ADD]], ptr [[I]], align 4, !dbg [[DBG103]]
// CHECK1-NEXT:      #dbg_declare(ptr [[F]], [[META104:![0-9]+]], !DIExpression(), [[META107:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 1, !dbg [[DBG108:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX]], i64 0, i64 1, !dbg [[DBG108]]
// CHECK1-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX7]], i64 0, i64 1, !dbg [[DBG108]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX8]], ptr [[F]], align 8, !dbg [[META107]]
// CHECK1-NEXT:      #dbg_declare(ptr [[G]], [[META109:![0-9]+]], !DIExpression(), [[META110:![0-9]+]])
// CHECK1-NEXT:    store ptr [[A_ADDR]], ptr [[G]], align 8, !dbg [[META110]]
// CHECK1-NEXT:      #dbg_declare(ptr [[H]], [[META111:![0-9]+]], !DIExpression(), [[META112:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[B4]], i64 0, i64 1, !dbg [[DBG113:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX9]], i64 0, i64 1, !dbg [[DBG113]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX10]], ptr [[H]], align 8, !dbg [[META112]]
// CHECK1-NEXT:      #dbg_declare(ptr [[D]], [[META114:![0-9]+]], !DIExpression(), [[META115:![0-9]+]])
// CHECK1-NEXT:    store i32 15, ptr [[D]], align 4, !dbg [[META115]]
// CHECK1-NEXT:    store i32 5, ptr [[A_ADDR]], align 4, !dbg [[DBG116:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[B4]], i64 0, i64 0, !dbg [[DBG117:![0-9]+]]
// CHECK1-NEXT:    [[TMP21:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG118:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP21]] to i64, !dbg [[DBG117]]
// CHECK1-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX11]], i64 0, i64 [[IDXPROM]], !dbg [[DBG117]]
// CHECK1-NEXT:    store i32 10, ptr [[ARRAYIDX12]], align 4, !dbg [[DBG119:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG120:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX13]], i64 0, i64 0, !dbg [[DBG120]]
// CHECK1-NEXT:    [[TMP22:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG121:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM15:%.*]] = sext i32 [[TMP22]] to i64, !dbg [[DBG120]]
// CHECK1-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX14]], i64 0, i64 [[IDXPROM15]], !dbg [[DBG120]]
// CHECK1-NEXT:    store i32 11, ptr [[ARRAYIDX16]], align 4, !dbg [[DBG122:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG123:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX17]], i64 0, i64 0, !dbg [[DBG123]]
// CHECK1-NEXT:    [[TMP23:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG124:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM19:%.*]] = sext i32 [[TMP23]] to i64, !dbg [[DBG123]]
// CHECK1-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX18]], i64 0, i64 [[IDXPROM19]], !dbg [[DBG123]]
// CHECK1-NEXT:    [[TMP24:%.*]] = load i32, ptr [[ARRAYIDX20]], align 4, !dbg [[DBG123]]
// CHECK1-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[B4]], i64 0, i64 0, !dbg [[DBG125:![0-9]+]]
// CHECK1-NEXT:    [[TMP25:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG126:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM22:%.*]] = sext i32 [[TMP25]] to i64, !dbg [[DBG125]]
// CHECK1-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX21]], i64 0, i64 [[IDXPROM22]], !dbg [[DBG125]]
// CHECK1-NEXT:    store i32 [[TMP24]], ptr [[ARRAYIDX23]], align 4, !dbg [[DBG127:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[B4]], i64 0, i64 0, !dbg [[DBG128:![0-9]+]]
// CHECK1-NEXT:    [[TMP26:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG129:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM25:%.*]] = sext i32 [[TMP26]] to i64, !dbg [[DBG128]]
// CHECK1-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX24]], i64 0, i64 [[IDXPROM25]], !dbg [[DBG128]]
// CHECK1-NEXT:    [[TMP27:%.*]] = load i32, ptr [[ARRAYIDX26]], align 4, !dbg [[DBG128]]
// CHECK1-NEXT:    [[TMP28:%.*]] = load i8, ptr [[TMP10]], align 1, !dbg [[DBG130:![0-9]+]]
// CHECK1-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP28]] to i1, !dbg [[DBG130]]
// CHECK1-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32, !dbg [[DBG130]]
// CHECK1-NEXT:    [[OR:%.*]] = or i32 [[CONV]], [[TMP27]], !dbg [[DBG130]]
// CHECK1-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[OR]], 0, !dbg [[DBG130]]
// CHECK1-NEXT:    [[STOREDV:%.*]] = zext i1 [[TOBOOL]] to i8, !dbg [[DBG130]]
// CHECK1-NEXT:    store i8 [[STOREDV]], ptr [[TMP10]], align 1, !dbg [[DBG130]]
// CHECK1-NEXT:    br label [[OMP_BODY_CONTINUE:%.*]], !dbg [[DBG131:![0-9]+]]
// CHECK1:       omp.body.continue:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_INC:%.*]], !dbg [[DBG102]]
// CHECK1:       omp.inner.for.inc:
// CHECK1-NEXT:    [[TMP29:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[ADD27:%.*]] = add nsw i32 [[TMP29]], 1, !dbg [[DBG93]]
// CHECK1-NEXT:    store i32 [[ADD27]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG93]]
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND]], !dbg [[DBG102]], !llvm.loop [[LOOP132:![0-9]+]]
// CHECK1:       omp.inner.for.end:
// CHECK1-NEXT:    br label [[OMP_DISPATCH_INC:%.*]], !dbg [[DBG102]]
// CHECK1:       omp.dispatch.inc:
// CHECK1-NEXT:    [[TMP30:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP31:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[ADD28:%.*]] = add nsw i32 [[TMP30]], [[TMP31]], !dbg [[DBG93]]
// CHECK1-NEXT:    store i32 [[ADD28]], ptr [[DOTOMP_LB]], align 4, !dbg [[DBG93]]
// CHECK1-NEXT:    [[TMP32:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[TMP33:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG96]]
// CHECK1-NEXT:    [[ADD29:%.*]] = add nsw i32 [[TMP32]], [[TMP33]], !dbg [[DBG93]]
// CHECK1-NEXT:    store i32 [[ADD29]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG93]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND]], !dbg [[DBG102]], !llvm.loop [[LOOP134:![0-9]+]]
// CHECK1:       omp.dispatch.end:
// CHECK1-NEXT:    call void @__kmpc_for_static_fini(ptr @[[GLOB5:[0-9]+]], i32 [[TMP12]]), !dbg [[DBG133:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG135:![0-9]+]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug___omp_outlined
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], i64 noundef [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG136:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META142:![0-9]+]], !DIExpression(), [[META143:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META144:![0-9]+]], !DIExpression(), [[META143]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META145:![0-9]+]], !DIExpression(), [[META143]])
// CHECK1-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META146:![0-9]+]], !DIExpression(), [[META143]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META147:![0-9]+]], !DIExpression(), [[META143]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META148:![0-9]+]], !DIExpression(), [[META143]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG149:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG149]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG149]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP4:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP3]], ptr null, ptr [[DOTGLOBAL_TID__ADDR]], i64 0, metadata [[META139:![0-9]+]]), !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[DOTBOUND_TID__ADDR]], align 8, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP6:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP5]], ptr null, ptr [[DOTBOUND_TID__ADDR]], i64 0, metadata [[META139]]), !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP11:%.*]] = addrspacecast ptr [[TMP7]] to ptr addrspace(1), !dbg [[DBG149]]
// CHECK1-NEXT:    [[TMP12:%.*]] = addrspacecast ptr [[TMP10]] to ptr addrspace(1), !dbg [[DBG149]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l13_debug___omp_outlined_debug__(ptr [[TMP4]], ptr [[TMP6]], ptr addrspace(1) [[TMP11]], i32 [[TMP8]], ptr [[TMP9]], ptr addrspace(1) [[TMP12]]) #[[ATTR4]], !dbg [[DBG149]]
// CHECK1-NEXT:    ret void, !dbg [[DBG149]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug__
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], i32 noundef [[A:%.*]], ptr addrspace(1) noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG150:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_CASTED:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[CAPTURED_VARS_ADDRS:%.*]] = alloca [4 x ptr], align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META158:![0-9]+]], !DIExpression(), [[META159:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META160:![0-9]+]], !DIExpression(), [[META161:![0-9]+]])
// CHECK1-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META162:![0-9]+]], !DIExpression(), [[META163:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META164:![0-9]+]], !DIExpression(), [[META165:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META166:![0-9]+]], !DIExpression(), [[META167:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG168:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META155:![0-9]+]]), !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG168]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG168]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr addrspace(1), ptr [[B_ADDR]], align 8, !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP4]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META155]]), !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP6:%.*]] = addrspacecast ptr addrspace(1) [[TMP5]] to ptr, !dbg [[DBG168]]
// CHECK1-NEXT:    store ptr [[TMP6]], ptr [[_TMP1]], align 8, !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG168]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP9:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP8]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META155]]), !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr addrspace(1) [[TMP9]] to ptr, !dbg [[DBG168]]
// CHECK1-NEXT:    store ptr [[TMP10]], ptr [[_TMP2]], align 8, !dbg [[DBG168]]
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG168]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP12:%.*]] = call i32 @__kmpc_target_init(ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_kernel_environment, ptr [[DYN_PTR]]), !dbg [[DBG168]]
// CHECK1-NEXT:    [[EXEC_USER_CODE:%.*]] = icmp eq i32 [[TMP12]], -1, !dbg [[DBG168]]
// CHECK1-NEXT:    br i1 [[EXEC_USER_CODE]], label [[USER_CODE_ENTRY:%.*]], label [[WORKER_EXIT:%.*]], !dbg [[DBG168]]
// CHECK1:       user_code.entry:
// CHECK1-NEXT:    [[TMP13:%.*]] = call i32 @__kmpc_global_thread_num(ptr @[[GLOB13:[0-9]+]]), !dbg [[DBG169:![0-9]+]]
// CHECK1-NEXT:    [[TMP14:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG171:![0-9]+]]
// CHECK1-NEXT:    store i32 [[TMP14]], ptr [[A_CASTED]], align 4, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP15:%.*]] = load i64, ptr [[A_CASTED]], align 8, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 0, !dbg [[DBG171]]
// CHECK1-NEXT:    store ptr [[TMP3]], ptr [[TMP16]], align 8, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP17:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 1, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP18:%.*]] = inttoptr i64 [[TMP15]] to ptr, !dbg [[DBG171]]
// CHECK1-NEXT:    store ptr [[TMP18]], ptr [[TMP17]], align 8, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 2, !dbg [[DBG171]]
// CHECK1-NEXT:    store ptr [[TMP7]], ptr [[TMP19]], align 8, !dbg [[DBG171]]
// CHECK1-NEXT:    [[TMP20:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 3, !dbg [[DBG171]]
// CHECK1-NEXT:    store ptr [[TMP11]], ptr [[TMP20]], align 8, !dbg [[DBG171]]
// CHECK1-NEXT:    call void @__kmpc_parallel_51(ptr @[[GLOB13]], i32 [[TMP13]], i32 1, i32 -1, i32 -1, ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug___omp_outlined, ptr null, ptr [[CAPTURED_VARS_ADDRS]], i64 4), !dbg [[DBG171]]
// CHECK1-NEXT:    call void @__kmpc_target_deinit(), !dbg [[DBG172:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG173:![0-9]+]]
// CHECK1:       worker.exit:
// CHECK1-NEXT:    ret void, !dbg [[DBG168]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], i64 noundef [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]]) #[[ATTR1]] !dbg [[DBG174:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META180:![0-9]+]], !DIExpression(), [[META181:![0-9]+]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META182:![0-9]+]], !DIExpression(), [[META181]])
// CHECK1-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META183:![0-9]+]], !DIExpression(), [[META181]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META184:![0-9]+]], !DIExpression(), [[META181]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META185:![0-9]+]], !DIExpression(), [[META181]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG186:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG186]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG186]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DYN_PTR_ADDR]], align 8, !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP4:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP3]], ptr null, ptr [[DYN_PTR_ADDR]], i64 0, metadata [[META177:![0-9]+]]), !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP9:%.*]] = addrspacecast ptr [[TMP5]] to ptr addrspace(1), !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr [[TMP7]] to ptr addrspace(1), !dbg [[DBG186]]
// CHECK1-NEXT:    [[TMP11:%.*]] = addrspacecast ptr [[TMP8]] to ptr addrspace(1), !dbg [[DBG186]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug__(ptr [[TMP4]], ptr addrspace(1) [[TMP9]], i32 [[TMP6]], ptr addrspace(1) [[TMP10]], ptr addrspace(1) [[TMP11]]) #[[ATTR4]], !dbg [[DBG186]]
// CHECK1-NEXT:    ret void, !dbg [[DBG186]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug___omp_outlined_debug__
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], i32 noundef [[A:%.*]], ptr addrspace(1) noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG187:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTOMP_IV:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[_TMP3:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_LB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_UB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[F:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[G:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[H:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META193:![0-9]+]], !DIExpression(), [[META194:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META195:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META196:![0-9]+]], !DIExpression(), [[META197:![0-9]+]])
// CHECK1-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META198:![0-9]+]], !DIExpression(), [[META199:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META200:![0-9]+]], !DIExpression(), [[META201:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META202:![0-9]+]], !DIExpression(), [[META203:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG204:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META190:![0-9]+]]), !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG204]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG204]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr addrspace(1), ptr [[B_ADDR]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP4]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META190]]), !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP6:%.*]] = addrspacecast ptr addrspace(1) [[TMP5]] to ptr, !dbg [[DBG204]]
// CHECK1-NEXT:    store ptr [[TMP6]], ptr [[_TMP1]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG204]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP9:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP8]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META190]]), !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr addrspace(1) [[TMP9]] to ptr, !dbg [[DBG204]]
// CHECK1-NEXT:    store ptr [[TMP10]], ptr [[_TMP2]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG204]], !nonnull [[META30]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IV]], [[META205:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_LB]], [[META206:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG207:![0-9]+]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_UB]], [[META208:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    store i32 9, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_STRIDE]], [[META209:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    store i32 1, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IS_LAST]], [[META210:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_IS_LAST]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:      #dbg_declare(ptr [[I]], [[META211:![0-9]+]], !DIExpression(), [[META194]])
// CHECK1-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4, !dbg [[DBG204]]
// CHECK1-NEXT:    call void @__kmpc_for_static_init_4(ptr @[[GLOB10:[0-9]+]], i32 [[TMP13]], i32 33, ptr [[DOTOMP_IS_LAST]], ptr [[DOTOMP_LB]], ptr [[DOTOMP_UB]], ptr [[DOTOMP_STRIDE]], i32 1, i32 1), !dbg [[DBG212:![0-9]+]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND:%.*]], !dbg [[DBG204]]
// CHECK1:       omp.dispatch.cond:
// CHECK1-NEXT:    [[TMP14:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP14]], 9, !dbg [[DBG207]]
// CHECK1-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]], !dbg [[DBG207]]
// CHECK1:       cond.true:
// CHECK1-NEXT:    br label [[COND_END:%.*]], !dbg [[DBG207]]
// CHECK1:       cond.false:
// CHECK1-NEXT:    [[TMP15:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    br label [[COND_END]], !dbg [[DBG207]]
// CHECK1:       cond.end:
// CHECK1-NEXT:    [[COND:%.*]] = phi i32 [ 9, [[COND_TRUE]] ], [ [[TMP15]], [[COND_FALSE]] ], !dbg [[DBG207]]
// CHECK1-NEXT:    store i32 [[COND]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP16:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    store i32 [[TMP16]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP17:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP18:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[CMP4:%.*]] = icmp sle i32 [[TMP17]], [[TMP18]], !dbg [[DBG204]]
// CHECK1-NEXT:    br i1 [[CMP4]], label [[OMP_DISPATCH_BODY:%.*]], label [[OMP_DISPATCH_END:%.*]], !dbg [[DBG204]]
// CHECK1:       omp.dispatch.body:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND:%.*]], !dbg [[DBG204]]
// CHECK1:       omp.inner.for.cond:
// CHECK1-NEXT:    [[TMP19:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP20:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[CMP5:%.*]] = icmp sle i32 [[TMP19]], [[TMP20]], !dbg [[DBG204]]
// CHECK1-NEXT:    br i1 [[CMP5]], label [[OMP_INNER_FOR_BODY:%.*]], label [[OMP_INNER_FOR_END:%.*]], !dbg [[DBG204]]
// CHECK1:       omp.inner.for.body:
// CHECK1-NEXT:    [[TMP21:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP21]], 1, !dbg [[DBG213:![0-9]+]]
// CHECK1-NEXT:    [[ADD:%.*]] = add nsw i32 0, [[MUL]], !dbg [[DBG213]]
// CHECK1-NEXT:    store i32 [[ADD]], ptr [[I]], align 4, !dbg [[DBG213]]
// CHECK1-NEXT:      #dbg_declare(ptr [[F]], [[META214:![0-9]+]], !DIExpression(), [[META216:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 1, !dbg [[DBG217:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX]], i64 0, i64 1, !dbg [[DBG217]]
// CHECK1-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX6]], i64 0, i64 1, !dbg [[DBG217]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX7]], ptr [[F]], align 8, !dbg [[META216]]
// CHECK1-NEXT:      #dbg_declare(ptr [[G]], [[META218:![0-9]+]], !DIExpression(), [[META219:![0-9]+]])
// CHECK1-NEXT:    store ptr [[A_ADDR]], ptr [[G]], align 8, !dbg [[META219]]
// CHECK1-NEXT:      #dbg_declare(ptr [[H]], [[META220:![0-9]+]], !DIExpression(), [[META221:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP7]], i64 0, i64 1, !dbg [[DBG222:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX8]], i64 0, i64 1, !dbg [[DBG222]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX9]], ptr [[H]], align 8, !dbg [[META221]]
// CHECK1-NEXT:      #dbg_declare(ptr [[D]], [[META223:![0-9]+]], !DIExpression(), [[META224:![0-9]+]])
// CHECK1-NEXT:    store i32 15, ptr [[D]], align 4, !dbg [[META224]]
// CHECK1-NEXT:    store i32 5, ptr [[A_ADDR]], align 4, !dbg [[DBG225:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP7]], i64 0, i64 0, !dbg [[DBG226:![0-9]+]]
// CHECK1-NEXT:    [[TMP22:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG227:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP22]] to i64, !dbg [[DBG226]]
// CHECK1-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX10]], i64 0, i64 [[IDXPROM]], !dbg [[DBG226]]
// CHECK1-NEXT:    store i32 10, ptr [[ARRAYIDX11]], align 4, !dbg [[DBG228:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG229:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX12]], i64 0, i64 0, !dbg [[DBG229]]
// CHECK1-NEXT:    [[TMP23:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG230:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM14:%.*]] = sext i32 [[TMP23]] to i64, !dbg [[DBG229]]
// CHECK1-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX13]], i64 0, i64 [[IDXPROM14]], !dbg [[DBG229]]
// CHECK1-NEXT:    store i32 11, ptr [[ARRAYIDX15]], align 4, !dbg [[DBG231:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG232:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX16]], i64 0, i64 0, !dbg [[DBG232]]
// CHECK1-NEXT:    [[TMP24:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG233:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM18:%.*]] = sext i32 [[TMP24]] to i64, !dbg [[DBG232]]
// CHECK1-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX17]], i64 0, i64 [[IDXPROM18]], !dbg [[DBG232]]
// CHECK1-NEXT:    [[TMP25:%.*]] = load i32, ptr [[ARRAYIDX19]], align 4, !dbg [[DBG232]]
// CHECK1-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP7]], i64 0, i64 0, !dbg [[DBG234:![0-9]+]]
// CHECK1-NEXT:    [[TMP26:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG235:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM21:%.*]] = sext i32 [[TMP26]] to i64, !dbg [[DBG234]]
// CHECK1-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX20]], i64 0, i64 [[IDXPROM21]], !dbg [[DBG234]]
// CHECK1-NEXT:    store i32 [[TMP25]], ptr [[ARRAYIDX22]], align 4, !dbg [[DBG236:![0-9]+]]
// CHECK1-NEXT:    [[TMP27:%.*]] = load i8, ptr [[TMP11]], align 1, !dbg [[DBG237:![0-9]+]]
// CHECK1-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP27]] to i1, !dbg [[DBG237]]
// CHECK1-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32, !dbg [[DBG237]]
// CHECK1-NEXT:    store i32 [[CONV]], ptr [[D]], align 4, !dbg [[DBG238:![0-9]+]]
// CHECK1-NEXT:    br label [[OMP_BODY_CONTINUE:%.*]], !dbg [[DBG239:![0-9]+]]
// CHECK1:       omp.body.continue:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_INC:%.*]], !dbg [[DBG212]]
// CHECK1:       omp.inner.for.inc:
// CHECK1-NEXT:    [[TMP28:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[ADD23:%.*]] = add nsw i32 [[TMP28]], 1, !dbg [[DBG204]]
// CHECK1-NEXT:    store i32 [[ADD23]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG204]]
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND]], !dbg [[DBG212]], !llvm.loop [[LOOP240:![0-9]+]]
// CHECK1:       omp.inner.for.end:
// CHECK1-NEXT:    br label [[OMP_DISPATCH_INC:%.*]], !dbg [[DBG212]]
// CHECK1:       omp.dispatch.inc:
// CHECK1-NEXT:    [[TMP29:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP30:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[ADD24:%.*]] = add nsw i32 [[TMP29]], [[TMP30]], !dbg [[DBG204]]
// CHECK1-NEXT:    store i32 [[ADD24]], ptr [[DOTOMP_LB]], align 4, !dbg [[DBG204]]
// CHECK1-NEXT:    [[TMP31:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[TMP32:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG207]]
// CHECK1-NEXT:    [[ADD25:%.*]] = add nsw i32 [[TMP31]], [[TMP32]], !dbg [[DBG204]]
// CHECK1-NEXT:    store i32 [[ADD25]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG204]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND]], !dbg [[DBG212]], !llvm.loop [[LOOP242:![0-9]+]]
// CHECK1:       omp.dispatch.end:
// CHECK1-NEXT:    call void @__kmpc_for_static_fini(ptr @[[GLOB12:[0-9]+]], i32 [[TMP13]]), !dbg [[DBG241:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG243:![0-9]+]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug___omp_outlined
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], i64 noundef [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG244:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META248:![0-9]+]], !DIExpression(), [[META249:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META250:![0-9]+]], !DIExpression(), [[META249]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META251:![0-9]+]], !DIExpression(), [[META249]])
// CHECK1-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META252:![0-9]+]], !DIExpression(), [[META249]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META253:![0-9]+]], !DIExpression(), [[META249]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META254:![0-9]+]], !DIExpression(), [[META249]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG255:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG255]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG255]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP4:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP3]], ptr null, ptr [[DOTGLOBAL_TID__ADDR]], i64 0, metadata [[META245:![0-9]+]]), !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[DOTBOUND_TID__ADDR]], align 8, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP6:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP5]], ptr null, ptr [[DOTBOUND_TID__ADDR]], i64 0, metadata [[META245]]), !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load i32, ptr [[A_ADDR]], align 4, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP11:%.*]] = addrspacecast ptr [[TMP7]] to ptr addrspace(1), !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP12:%.*]] = addrspacecast ptr [[TMP9]] to ptr addrspace(1), !dbg [[DBG255]]
// CHECK1-NEXT:    [[TMP13:%.*]] = addrspacecast ptr [[TMP10]] to ptr addrspace(1), !dbg [[DBG255]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l27_debug___omp_outlined_debug__(ptr [[TMP4]], ptr [[TMP6]], ptr addrspace(1) [[TMP11]], i32 [[TMP8]], ptr addrspace(1) [[TMP12]], ptr addrspace(1) [[TMP13]]) #[[ATTR4]], !dbg [[DBG255]]
// CHECK1-NEXT:    ret void, !dbg [[DBG255]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug__
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], ptr addrspace(1) noalias noundef [[A:%.*]], ptr addrspace(1) noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG256:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP3:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[CAPTURED_VARS_ADDRS:%.*]] = alloca [4 x ptr], align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META264:![0-9]+]], !DIExpression(), [[META265:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META266:![0-9]+]], !DIExpression(), [[META267:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META268:![0-9]+]], !DIExpression(), [[META269:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META270:![0-9]+]], !DIExpression(), [[META271:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META272:![0-9]+]], !DIExpression(), [[META273:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG274:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META261:![0-9]+]]), !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG274]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG274]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr addrspace(1), ptr [[A_ADDR]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP4]], ptr null, ptr [[A_ADDR]], i64 0, metadata [[META261]]), !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP6:%.*]] = addrspacecast ptr addrspace(1) [[TMP5]] to ptr, !dbg [[DBG274]]
// CHECK1-NEXT:    store ptr [[TMP6]], ptr [[_TMP1]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG274]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr addrspace(1), ptr [[B_ADDR]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP9:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP8]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META261]]), !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr addrspace(1) [[TMP9]] to ptr, !dbg [[DBG274]]
// CHECK1-NEXT:    store ptr [[TMP10]], ptr [[_TMP2]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG274]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP12:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP13:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP12]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META261]]), !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP14:%.*]] = addrspacecast ptr addrspace(1) [[TMP13]] to ptr, !dbg [[DBG274]]
// CHECK1-NEXT:    store ptr [[TMP14]], ptr [[_TMP3]], align 8, !dbg [[DBG274]]
// CHECK1-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[_TMP3]], align 8, !dbg [[DBG274]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP16:%.*]] = call i32 @__kmpc_target_init(ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_kernel_environment, ptr [[DYN_PTR]]), !dbg [[DBG274]]
// CHECK1-NEXT:    [[EXEC_USER_CODE:%.*]] = icmp eq i32 [[TMP16]], -1, !dbg [[DBG274]]
// CHECK1-NEXT:    br i1 [[EXEC_USER_CODE]], label [[USER_CODE_ENTRY:%.*]], label [[WORKER_EXIT:%.*]], !dbg [[DBG274]]
// CHECK1:       user_code.entry:
// CHECK1-NEXT:    [[TMP17:%.*]] = call i32 @__kmpc_global_thread_num(ptr @[[GLOB20:[0-9]+]]), !dbg [[DBG275:![0-9]+]]
// CHECK1-NEXT:    [[TMP18:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 0, !dbg [[DBG277:![0-9]+]]
// CHECK1-NEXT:    store ptr [[TMP3]], ptr [[TMP18]], align 8, !dbg [[DBG277]]
// CHECK1-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 1, !dbg [[DBG277]]
// CHECK1-NEXT:    store ptr [[TMP7]], ptr [[TMP19]], align 8, !dbg [[DBG277]]
// CHECK1-NEXT:    [[TMP20:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 2, !dbg [[DBG277]]
// CHECK1-NEXT:    store ptr [[TMP11]], ptr [[TMP20]], align 8, !dbg [[DBG277]]
// CHECK1-NEXT:    [[TMP21:%.*]] = getelementptr inbounds [4 x ptr], ptr [[CAPTURED_VARS_ADDRS]], i64 0, i64 3, !dbg [[DBG277]]
// CHECK1-NEXT:    store ptr [[TMP15]], ptr [[TMP21]], align 8, !dbg [[DBG277]]
// CHECK1-NEXT:    call void @__kmpc_parallel_51(ptr @[[GLOB20]], i32 [[TMP17]], i32 1, i32 -1, i32 -1, ptr @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug___omp_outlined, ptr null, ptr [[CAPTURED_VARS_ADDRS]], i64 4), !dbg [[DBG277]]
// CHECK1-NEXT:    call void @__kmpc_target_deinit(), !dbg [[DBG278:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG279:![0-9]+]]
// CHECK1:       worker.exit:
// CHECK1-NEXT:    ret void, !dbg [[DBG274]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41
// CHECK1-SAME: (ptr noalias noundef [[DYN_PTR:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]]) #[[ATTR1]] !dbg [[DBG280:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DYN_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    store ptr [[DYN_PTR]], ptr [[DYN_PTR_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DYN_PTR_ADDR]], [[META286:![0-9]+]], !DIExpression(), [[META287:![0-9]+]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META288:![0-9]+]], !DIExpression(), [[META287]])
// CHECK1-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META289:![0-9]+]], !DIExpression(), [[META287]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META290:![0-9]+]], !DIExpression(), [[META287]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META291:![0-9]+]], !DIExpression(), [[META287]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG292:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !dbg [[DBG292]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG292]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG292]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DYN_PTR_ADDR]], align 8, !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP4]], ptr null, ptr [[DYN_PTR_ADDR]], i64 0, metadata [[META283:![0-9]+]]), !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr [[TMP6]] to ptr addrspace(1), !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP11:%.*]] = addrspacecast ptr [[TMP7]] to ptr addrspace(1), !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP12:%.*]] = addrspacecast ptr [[TMP8]] to ptr addrspace(1), !dbg [[DBG292]]
// CHECK1-NEXT:    [[TMP13:%.*]] = addrspacecast ptr [[TMP9]] to ptr addrspace(1), !dbg [[DBG292]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug__(ptr [[TMP5]], ptr addrspace(1) [[TMP10]], ptr addrspace(1) [[TMP11]], ptr addrspace(1) [[TMP12]], ptr addrspace(1) [[TMP13]]) #[[ATTR4]], !dbg [[DBG292]]
// CHECK1-NEXT:    ret void, !dbg [[DBG292]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug___omp_outlined_debug__
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr addrspace(1) noalias noundef [[C:%.*]], ptr addrspace(1) noalias noundef [[A:%.*]], ptr addrspace(1) noalias noundef [[B:%.*]], ptr addrspace(1) noalias noundef [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG293:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr addrspace(1), align 8
// CHECK1-NEXT:    [[TMP:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP1:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP2:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[_TMP3:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTOMP_IV:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[_TMP4:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_LB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_UB:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    [[F:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[G:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[H:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META299:![0-9]+]], !DIExpression(), [[META300:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META301:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    store ptr addrspace(1) [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META302:![0-9]+]], !DIExpression(), [[META303:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META304:![0-9]+]], !DIExpression(), [[META305:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META306:![0-9]+]], !DIExpression(), [[META307:![0-9]+]])
// CHECK1-NEXT:    store ptr addrspace(1) [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META308:![0-9]+]], !DIExpression(), [[META309:![0-9]+]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[C_ADDR]], align 8, !dbg [[DBG310:![0-9]+]]
// CHECK1-NEXT:    [[TMP1:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP0]], ptr null, ptr [[C_ADDR]], i64 0, metadata [[META296:![0-9]+]]), !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(1) [[TMP1]] to ptr, !dbg [[DBG310]]
// CHECK1-NEXT:    store ptr [[TMP2]], ptr [[TMP]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !dbg [[DBG310]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr addrspace(1), ptr [[A_ADDR]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP4]], ptr null, ptr [[A_ADDR]], i64 0, metadata [[META296]]), !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP6:%.*]] = addrspacecast ptr addrspace(1) [[TMP5]] to ptr, !dbg [[DBG310]]
// CHECK1-NEXT:    store ptr [[TMP6]], ptr [[_TMP1]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[_TMP1]], align 8, !dbg [[DBG310]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr addrspace(1), ptr [[B_ADDR]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP9:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP8]], ptr null, ptr [[B_ADDR]], i64 0, metadata [[META296]]), !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP10:%.*]] = addrspacecast ptr addrspace(1) [[TMP9]] to ptr, !dbg [[DBG310]]
// CHECK1-NEXT:    store ptr [[TMP10]], ptr [[_TMP2]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[_TMP2]], align 8, !dbg [[DBG310]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP12:%.*]] = load ptr addrspace(1), ptr [[BB_ADDR]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP13:%.*]] = call ptr addrspace(1) @llvm.noalias.p1.p0.p0.i64(ptr addrspace(1) [[TMP12]], ptr null, ptr [[BB_ADDR]], i64 0, metadata [[META296]]), !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP14:%.*]] = addrspacecast ptr addrspace(1) [[TMP13]] to ptr, !dbg [[DBG310]]
// CHECK1-NEXT:    store ptr [[TMP14]], ptr [[_TMP3]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[_TMP3]], align 8, !dbg [[DBG310]], !nonnull [[META30]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IV]], [[META311:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_LB]], [[META312:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG313:![0-9]+]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_UB]], [[META314:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    store i32 9, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_STRIDE]], [[META315:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    store i32 1, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTOMP_IS_LAST]], [[META316:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    store i32 0, ptr [[DOTOMP_IS_LAST]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:      #dbg_declare(ptr [[I]], [[META317:![0-9]+]], !DIExpression(), [[META300]])
// CHECK1-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP17:%.*]] = load i32, ptr [[TMP16]], align 4, !dbg [[DBG310]]
// CHECK1-NEXT:    call void @__kmpc_for_static_init_4(ptr @[[GLOB17:[0-9]+]], i32 [[TMP17]], i32 33, ptr [[DOTOMP_IS_LAST]], ptr [[DOTOMP_LB]], ptr [[DOTOMP_UB]], ptr [[DOTOMP_STRIDE]], i32 1, i32 1), !dbg [[DBG318:![0-9]+]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND:%.*]], !dbg [[DBG310]]
// CHECK1:       omp.dispatch.cond:
// CHECK1-NEXT:    [[TMP18:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP18]], 9, !dbg [[DBG313]]
// CHECK1-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]], !dbg [[DBG313]]
// CHECK1:       cond.true:
// CHECK1-NEXT:    br label [[COND_END:%.*]], !dbg [[DBG313]]
// CHECK1:       cond.false:
// CHECK1-NEXT:    [[TMP19:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    br label [[COND_END]], !dbg [[DBG313]]
// CHECK1:       cond.end:
// CHECK1-NEXT:    [[COND:%.*]] = phi i32 [ 9, [[COND_TRUE]] ], [ [[TMP19]], [[COND_FALSE]] ], !dbg [[DBG313]]
// CHECK1-NEXT:    store i32 [[COND]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP20:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    store i32 [[TMP20]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP21:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP22:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[CMP5:%.*]] = icmp sle i32 [[TMP21]], [[TMP22]], !dbg [[DBG310]]
// CHECK1-NEXT:    br i1 [[CMP5]], label [[OMP_DISPATCH_BODY:%.*]], label [[OMP_DISPATCH_END:%.*]], !dbg [[DBG310]]
// CHECK1:       omp.dispatch.body:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND:%.*]], !dbg [[DBG310]]
// CHECK1:       omp.inner.for.cond:
// CHECK1-NEXT:    [[TMP23:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP24:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[CMP6:%.*]] = icmp sle i32 [[TMP23]], [[TMP24]], !dbg [[DBG310]]
// CHECK1-NEXT:    br i1 [[CMP6]], label [[OMP_INNER_FOR_BODY:%.*]], label [[OMP_INNER_FOR_END:%.*]], !dbg [[DBG310]]
// CHECK1:       omp.inner.for.body:
// CHECK1-NEXT:    [[TMP25:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP25]], 1, !dbg [[DBG319:![0-9]+]]
// CHECK1-NEXT:    [[ADD:%.*]] = add nsw i32 0, [[MUL]], !dbg [[DBG319]]
// CHECK1-NEXT:    store i32 [[ADD]], ptr [[I]], align 4, !dbg [[DBG319]]
// CHECK1-NEXT:      #dbg_declare(ptr [[F]], [[META320:![0-9]+]], !DIExpression(), [[META322:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 1, !dbg [[DBG323:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX]], i64 0, i64 1, !dbg [[DBG323]]
// CHECK1-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX7]], i64 0, i64 1, !dbg [[DBG323]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX8]], ptr [[F]], align 8, !dbg [[META322]]
// CHECK1-NEXT:      #dbg_declare(ptr [[G]], [[META324:![0-9]+]], !DIExpression(), [[META325:![0-9]+]])
// CHECK1-NEXT:    store ptr [[TMP7]], ptr [[G]], align 8, !dbg [[META325]]
// CHECK1-NEXT:      #dbg_declare(ptr [[H]], [[META326:![0-9]+]], !DIExpression(), [[META327:![0-9]+]])
// CHECK1-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP11]], i64 0, i64 1, !dbg [[DBG328:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX9]], i64 0, i64 1, !dbg [[DBG328]]
// CHECK1-NEXT:    store ptr [[ARRAYIDX10]], ptr [[H]], align 8, !dbg [[META327]]
// CHECK1-NEXT:      #dbg_declare(ptr [[D]], [[META329:![0-9]+]], !DIExpression(), [[META330:![0-9]+]])
// CHECK1-NEXT:    store i32 15, ptr [[D]], align 4, !dbg [[META330]]
// CHECK1-NEXT:    store i32 5, ptr [[TMP7]], align 4, !dbg [[DBG331:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP11]], i64 0, i64 0, !dbg [[DBG332:![0-9]+]]
// CHECK1-NEXT:    [[TMP26:%.*]] = load i32, ptr [[TMP7]], align 4, !dbg [[DBG333:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP26]] to i64, !dbg [[DBG332]]
// CHECK1-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX11]], i64 0, i64 [[IDXPROM]], !dbg [[DBG332]]
// CHECK1-NEXT:    store i32 10, ptr [[ARRAYIDX12]], align 4, !dbg [[DBG334:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG335:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX13]], i64 0, i64 0, !dbg [[DBG335]]
// CHECK1-NEXT:    [[TMP27:%.*]] = load i32, ptr [[TMP7]], align 4, !dbg [[DBG336:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM15:%.*]] = sext i32 [[TMP27]] to i64, !dbg [[DBG335]]
// CHECK1-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX14]], i64 0, i64 [[IDXPROM15]], !dbg [[DBG335]]
// CHECK1-NEXT:    store i32 11, ptr [[ARRAYIDX16]], align 4, !dbg [[DBG337:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds [10 x [10 x [10 x i32]]], ptr [[TMP3]], i64 0, i64 0, !dbg [[DBG338:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[ARRAYIDX17]], i64 0, i64 0, !dbg [[DBG338]]
// CHECK1-NEXT:    [[TMP28:%.*]] = load i32, ptr [[TMP7]], align 4, !dbg [[DBG339:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM19:%.*]] = sext i32 [[TMP28]] to i64, !dbg [[DBG338]]
// CHECK1-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX18]], i64 0, i64 [[IDXPROM19]], !dbg [[DBG338]]
// CHECK1-NEXT:    [[TMP29:%.*]] = load i32, ptr [[ARRAYIDX20]], align 4, !dbg [[DBG338]]
// CHECK1-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP11]], i64 0, i64 0, !dbg [[DBG340:![0-9]+]]
// CHECK1-NEXT:    [[TMP30:%.*]] = load i32, ptr [[TMP7]], align 4, !dbg [[DBG341:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM22:%.*]] = sext i32 [[TMP30]] to i64, !dbg [[DBG340]]
// CHECK1-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX21]], i64 0, i64 [[IDXPROM22]], !dbg [[DBG340]]
// CHECK1-NEXT:    store i32 [[TMP29]], ptr [[ARRAYIDX23]], align 4, !dbg [[DBG342:![0-9]+]]
// CHECK1-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds [10 x [10 x i32]], ptr [[TMP11]], i64 0, i64 0, !dbg [[DBG343:![0-9]+]]
// CHECK1-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP7]], align 4, !dbg [[DBG344:![0-9]+]]
// CHECK1-NEXT:    [[IDXPROM25:%.*]] = sext i32 [[TMP31]] to i64, !dbg [[DBG343]]
// CHECK1-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAYIDX24]], i64 0, i64 [[IDXPROM25]], !dbg [[DBG343]]
// CHECK1-NEXT:    [[TMP32:%.*]] = load i32, ptr [[ARRAYIDX26]], align 4, !dbg [[DBG343]]
// CHECK1-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP32]], 0, !dbg [[DBG343]]
// CHECK1-NEXT:    [[STOREDV:%.*]] = zext i1 [[TOBOOL]] to i8, !dbg [[DBG345:![0-9]+]]
// CHECK1-NEXT:    store i8 [[STOREDV]], ptr [[TMP15]], align 1, !dbg [[DBG345]]
// CHECK1-NEXT:    br label [[OMP_BODY_CONTINUE:%.*]], !dbg [[DBG346:![0-9]+]]
// CHECK1:       omp.body.continue:
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_INC:%.*]], !dbg [[DBG318]]
// CHECK1:       omp.inner.for.inc:
// CHECK1-NEXT:    [[TMP33:%.*]] = load i32, ptr [[DOTOMP_IV]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[ADD27:%.*]] = add nsw i32 [[TMP33]], 1, !dbg [[DBG310]]
// CHECK1-NEXT:    store i32 [[ADD27]], ptr [[DOTOMP_IV]], align 4, !dbg [[DBG310]]
// CHECK1-NEXT:    br label [[OMP_INNER_FOR_COND]], !dbg [[DBG318]], !llvm.loop [[LOOP347:![0-9]+]]
// CHECK1:       omp.inner.for.end:
// CHECK1-NEXT:    br label [[OMP_DISPATCH_INC:%.*]], !dbg [[DBG318]]
// CHECK1:       omp.dispatch.inc:
// CHECK1-NEXT:    [[TMP34:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP35:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[ADD28:%.*]] = add nsw i32 [[TMP34]], [[TMP35]], !dbg [[DBG310]]
// CHECK1-NEXT:    store i32 [[ADD28]], ptr [[DOTOMP_LB]], align 4, !dbg [[DBG310]]
// CHECK1-NEXT:    [[TMP36:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[TMP37:%.*]] = load i32, ptr [[DOTOMP_STRIDE]], align 4, !dbg [[DBG313]]
// CHECK1-NEXT:    [[ADD29:%.*]] = add nsw i32 [[TMP36]], [[TMP37]], !dbg [[DBG310]]
// CHECK1-NEXT:    store i32 [[ADD29]], ptr [[DOTOMP_UB]], align 4, !dbg [[DBG310]]
// CHECK1-NEXT:    br label [[OMP_DISPATCH_COND]], !dbg [[DBG318]], !llvm.loop [[LOOP349:![0-9]+]]
// CHECK1:       omp.dispatch.end:
// CHECK1-NEXT:    call void @__kmpc_for_static_fini(ptr @[[GLOB19:[0-9]+]], i32 [[TMP17]]), !dbg [[DBG348:![0-9]+]]
// CHECK1-NEXT:    ret void, !dbg [[DBG350:![0-9]+]]
//
//
// CHECK1-LABEL: define {{[^@]+}}@{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug___omp_outlined
// CHECK1-SAME: (ptr noalias noundef [[DOTGLOBAL_TID_:%.*]], ptr noalias noundef [[DOTBOUND_TID_:%.*]], ptr noundef nonnull align 4 dereferenceable(4000) [[C:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[A:%.*]], ptr noundef nonnull align 4 dereferenceable(400) [[B:%.*]], ptr noundef nonnull align 1 dereferenceable(1) [[BB:%.*]]) #[[ATTR0]] !dbg [[DBG351:![0-9]+]] {{.*}}{
// CHECK1-NEXT:  entry:
// CHECK1-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[DOTBOUND_TID__ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[C_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    [[BB_ADDR:%.*]] = alloca ptr, align 8
// CHECK1-NEXT:    store ptr [[DOTGLOBAL_TID_]], ptr [[DOTGLOBAL_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTGLOBAL_TID__ADDR]], [[META357:![0-9]+]], !DIExpression(), [[META358:![0-9]+]])
// CHECK1-NEXT:    store ptr [[DOTBOUND_TID_]], ptr [[DOTBOUND_TID__ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[DOTBOUND_TID__ADDR]], [[META359:![0-9]+]], !DIExpression(), [[META358]])
// CHECK1-NEXT:    store ptr [[C]], ptr [[C_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[C_ADDR]], [[META360:![0-9]+]], !DIExpression(), [[META358]])
// CHECK1-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[A_ADDR]], [[META361:![0-9]+]], !DIExpression(), [[META358]])
// CHECK1-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[B_ADDR]], [[META362:![0-9]+]], !DIExpression(), [[META358]])
// CHECK1-NEXT:    store ptr [[BB]], ptr [[BB_ADDR]], align 8
// CHECK1-NEXT:      #dbg_declare(ptr [[BB_ADDR]], [[META363:![0-9]+]], !DIExpression(), [[META358]])
// CHECK1-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG364:![0-9]+]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !dbg [[DBG364]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG364]], !nonnull [[META30]], !align [[META47]]
// CHECK1-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG364]], !nonnull [[META30]]
// CHECK1-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTGLOBAL_TID__ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP5:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP4]], ptr null, ptr [[DOTGLOBAL_TID__ADDR]], i64 0, metadata [[META354:![0-9]+]]), !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTBOUND_TID__ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP7:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP6]], ptr null, ptr [[DOTBOUND_TID__ADDR]], i64 0, metadata [[META354]]), !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[C_ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[B_ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[BB_ADDR]], align 8, !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP12:%.*]] = addrspacecast ptr [[TMP8]] to ptr addrspace(1), !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP13:%.*]] = addrspacecast ptr [[TMP9]] to ptr addrspace(1), !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP14:%.*]] = addrspacecast ptr [[TMP10]] to ptr addrspace(1), !dbg [[DBG364]]
// CHECK1-NEXT:    [[TMP15:%.*]] = addrspacecast ptr [[TMP11]] to ptr addrspace(1), !dbg [[DBG364]]
// CHECK1-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+}}_main_l41_debug___omp_outlined_debug__(ptr [[TMP5]], ptr [[TMP7]], ptr addrspace(1) [[TMP12]], ptr addrspace(1) [[TMP13]], ptr addrspace(1) [[TMP14]], ptr addrspace(1) [[TMP15]]) #[[ATTR4]], !dbg [[DBG364]]
// CHECK1-NEXT:    ret void, !dbg [[DBG364]]
//
