; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -instcombine -S < %s | FileCheck %s

define void @test01(i8* %ptr) {
; CHECK-LABEL: @test01(
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr
  ret void
}

define void @test02(i8* %ptr) {
; CHECK-LABEL: @test02(
; CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata !0)
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !alias.scope !0
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !alias.scope !0
  ret void
}

define void @test03(i8* %ptr) {
; CHECK-LABEL: @test03(
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !alias.scope !3
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !alias.scope !4
  ret void
}

define void @test04(i8* %ptr) {
; CHECK-LABEL: @test04(
; CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata !0)
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !alias.scope !4
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !alias.scope !5
  ret void
}

define void @test11(i8* %ptr) {
; CHECK-LABEL: @test11(
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !noalias !0
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !noalias !0
  ret void
}

define void @test12(i8* %ptr) {
; CHECK-LABEL: @test12(
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !noalias !3
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !noalias !4
  ret void
}

define void @test13(i8* %ptr) {
; CHECK-LABEL: @test13(
; CHECK-NEXT:    store i8 42, i8* [[PTR:%.*]], align 1, !noalias !4
; CHECK-NEXT:    ret void
;
  call void @llvm.experimental.noalias.scope.decl(metadata !0)
  store i8 42, i8* %ptr, !noalias !5
  ret void
}

declare void @llvm.experimental.noalias.scope.decl(metadata)

!0 = !{ !1 }
!1 = distinct !{ !1, !2 }
!2 = distinct !{ !2 }
!3 = !{ !4 }
!4 = distinct !{ !4, !2 }
!5 = !{ !1, !4 }
