// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -O1 -disable-llvm-optzns -ffull-restrict %s -emit-llvm -o - | FileCheck %s

int r;
void ex1(int *);

int *a;
// CHECK-LABEL: define dso_local ptr @foo(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[X]]) #[[ATTR5:[0-9]+]], !noalias !2
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr @llvm.noalias.decl.p0.p0.i64(ptr [[X]], i64 0, metadata [[META2:![0-9]+]]), !noalias !2
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr @a, align 8, !tbaa [[TBAA5:![0-9]+]], !noalias !2
// CHECK-NEXT:    store ptr [[TMP1]], ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !2
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !2
// CHECK-NEXT:    [[TMP3:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP2]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META2]]), !tbaa [[TBAA5]], !noalias !2
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr [[X]]) #[[ATTR5]]
// CHECK-NEXT:    ret ptr [[TMP3]]
//
int *foo() {
  int *restrict x = a;
  return x;

}

int *a2;
// CHECK-LABEL: define dso_local ptr @foo1(
// CHECK-SAME: i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[X:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[X2:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4, !tbaa [[TBAA9:![0-9]+]], !noalias !11
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[X]]) #[[ATTR5]], !noalias !11
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr @llvm.noalias.decl.p0.p0.i64(ptr [[X]], i64 0, metadata [[META11:![0-9]+]]), !noalias !11
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[B_ADDR]], align 4, !tbaa [[TBAA9]], !noalias !11
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
// CHECK:       if.then:
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr @a, align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP4:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP3]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr @r, align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP6]], [[TMP5]]
// CHECK-NEXT:    store i32 [[ADD]], ptr @r, align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP8:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP7]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    call void @ex1(ptr noundef [[TMP8]]), !noalias !14
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP10:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP9]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP10]], i32 1
// CHECK-NEXT:    store ptr [[INCDEC_PTR]], ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr @r, align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP13:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP12]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[TMP13]], align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP15:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP14]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    call void @ex1(ptr noundef [[TMP15]]), !noalias !14
// CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[B_ADDR]], align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP18:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP17]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP16]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP18]], i64 [[IDX_EXT]]
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr @r, align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP21:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP20]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    store i32 [[TMP19]], ptr [[TMP21]], align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP23:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP22]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    call void @ex1(ptr noundef [[TMP23]]), !noalias !14
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[X2]]) #[[ATTR5]], !noalias !14
// CHECK-NEXT:    [[TMP24:%.*]] = call ptr @llvm.noalias.decl.p0.p0.i64(ptr [[X2]], i64 0, metadata [[META16:![0-9]+]]), !noalias !14
// CHECK-NEXT:    [[TMP25:%.*]] = load ptr, ptr @a2, align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    store ptr [[TMP25]], ptr [[X2]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr @r, align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP27:%.*]] = load ptr, ptr [[X2]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP28:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP27]], ptr [[TMP24]], ptr [[X2]], i64 0, metadata [[META16]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    store i32 [[TMP26]], ptr [[TMP28]], align 4, !tbaa [[TBAA9]], !noalias !14
// CHECK-NEXT:    [[TMP29:%.*]] = load ptr, ptr [[X2]], align 8, !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    [[TMP30:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP29]], ptr [[TMP24]], ptr [[X2]], i64 0, metadata [[META16]]), !tbaa [[TBAA5]], !noalias !14
// CHECK-NEXT:    call void @ex1(ptr noundef [[TMP30]]), !noalias !14
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr [[X2]]) #[[ATTR5]], !noalias !11
// CHECK-NEXT:    br label [[IF_END:%.*]]
// CHECK:       if.else:
// CHECK-NEXT:    [[TMP31:%.*]] = load ptr, ptr @a2, align 8, !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    store ptr [[TMP31]], ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    [[TMP32:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    [[TMP33:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP32]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[TMP33]], align 4, !tbaa [[TBAA9]], !noalias !11
// CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr @r, align 4, !tbaa [[TBAA9]], !noalias !11
// CHECK-NEXT:    [[ADD1:%.*]] = add nsw i32 [[TMP35]], [[TMP34]]
// CHECK-NEXT:    store i32 [[ADD1]], ptr @r, align 4, !tbaa [[TBAA9]], !noalias !11
// CHECK-NEXT:    br label [[IF_END]]
// CHECK:       if.end:
// CHECK-NEXT:    [[TMP36:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    [[TMP37:%.*]] = call ptr @llvm.noalias.p0.p0.p0.i64(ptr [[TMP36]], ptr [[TMP0]], ptr [[X]], i64 0, metadata [[META11]]), !tbaa [[TBAA5]], !noalias !11
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr [[X]]) #[[ATTR5]]
// CHECK-NEXT:    ret ptr [[TMP37]]
//
int *foo1(int b) {
  int *restrict x;

  if (b) {
    x = a;
    r += *x;
    ex1(x);

    ++x;
    *x = r;
    ex1(x);

    x += b;
    *x = r;
    ex1(x);

    int *restrict x2 = a2;
    *x2 = r;
    ex1(x2);
  } else {
    x = a2;
    r += *x;
  }

  return x;
}

// CHECK-LABEL: define dso_local ptr @bar(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[X]]) #[[ATTR5]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @a, align 8, !tbaa [[TBAA5]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[X]], align 8, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[X]], align 8, !tbaa [[TBAA5]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr [[X]]) #[[ATTR5]]
// CHECK-NEXT:    ret ptr [[TMP1]]
//
int *bar() {
  int *x = a;
  return x;
}
