// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -O2 -ffull-restrict %s -emit-llvm -o - | FileCheck %s

// NOTE: SROA needs to be able to see through <tt>llvm.noalias</tt>. This is introduced in case of returning of larger structs.
struct A {
  int a, b, c, d, e, f, g, h;
};
// CHECK-LABEL: define dso_local void @constructIt(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret([[STRUCT_A:%.*]]) align 4 captures(none) initializes((0, 32)) [[AGG_RESULT:%.*]], i32 noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    store i32 [[A]], ptr [[AGG_RESULT]], align 4, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 4
// CHECK-NEXT:    store i32 [[A]], ptr [[B]], align 4, !tbaa [[TBAA7:![0-9]+]]
// CHECK-NEXT:    [[C:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 8
// CHECK-NEXT:    store i32 [[A]], ptr [[C]], align 4, !tbaa [[TBAA8:![0-9]+]]
// CHECK-NEXT:    [[D:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 12
// CHECK-NEXT:    store i32 [[A]], ptr [[D]], align 4, !tbaa [[TBAA9:![0-9]+]]
// CHECK-NEXT:    [[E:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 16
// CHECK-NEXT:    store i32 [[A]], ptr [[E]], align 4, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    [[F:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 20
// CHECK-NEXT:    store i32 [[A]], ptr [[F]], align 4, !tbaa [[TBAA11:![0-9]+]]
// CHECK-NEXT:    [[G:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 24
// CHECK-NEXT:    store i32 [[A]], ptr [[G]], align 4, !tbaa [[TBAA12:![0-9]+]]
// CHECK-NEXT:    [[H:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 28
// CHECK-NEXT:    store i32 [[A]], ptr [[H]], align 4, !tbaa [[TBAA13:![0-9]+]]
// CHECK-NEXT:    ret void
//
struct A constructIt(int a) {
  struct A tmp = {a, a, a, a, a, a, a, a};
  return tmp;
}


// Next functions must be identical (except for the name)
// CHECK-LABEL: define dso_local i32 @test_sroa01a(
// CHECK-SAME: i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP4_NOT:%.*]] = icmp eq i32 [[C]], 0
// CHECK-NEXT:    br i1 [[CMP4_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER:.*]]
// CHECK:       [[FOR_BODY_PREHEADER]]:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[C]], -1
// CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i33
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], -2
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i33
// CHECK-NEXT:    [[TMP4:%.*]] = mul i33 [[TMP1]], [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i33 [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = trunc nuw i33 [[TMP5]] to i32
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[C]], [[TMP6]]
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], -1
// CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[TMP_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP8]], %[[FOR_BODY_PREHEADER]] ]
// CHECK-NEXT:    ret i32 [[TMP_0_LCSSA]]
//
int test_sroa01a(unsigned c) {
  int tmp = 0;
  for (int i = 0; i < c; ++i) {
    struct A a = constructIt(i);
    tmp = tmp + a.e;
  }
  return tmp;
}



// CHECK-LABEL: define dso_local i32 @test_sroa01b(
// CHECK-SAME: i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp eq i32 [[C]], 0
// CHECK-NEXT:    br i1 [[CMP14_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER:.*]]
// CHECK:       [[FOR_BODY_PREHEADER]]:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[C]], -1
// CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i33
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], -2
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i33
// CHECK-NEXT:    [[TMP4:%.*]] = mul i33 [[TMP1]], [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i33 [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = trunc nuw i33 [[TMP5]] to i32
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[C]], [[TMP6]]
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], -1
// CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[TMP_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP8]], %[[FOR_BODY_PREHEADER]] ]
// CHECK-NEXT:    ret i32 [[TMP_0_LCSSA]]
//
int test_sroa01b(unsigned c) {
  int tmp = 0;
  for (int i = 0; i < c; ++i) {
    struct A a = {i, i, i, i, i, i, i, i};
    tmp = tmp + a.e;
  }
  return tmp;
}



// CHECK-LABEL: define dso_local i32 @test_sroa01c(
// CHECK-SAME: i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp eq i32 [[C]], 0
// CHECK-NEXT:    br i1 [[CMP14_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER:.*]]
// CHECK:       [[FOR_BODY_PREHEADER]]:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[C]], -1
// CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i33
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], -2
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i33
// CHECK-NEXT:    [[TMP4:%.*]] = mul i33 [[TMP1]], [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i33 [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = trunc nuw i33 [[TMP5]] to i32
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[C]], [[TMP6]]
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], -1
// CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[TMP_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP8]], %[[FOR_BODY_PREHEADER]] ]
// CHECK-NEXT:    ret i32 [[TMP_0_LCSSA]]
//
int test_sroa01c(unsigned c) {
  int tmp = 0;
  for (int i = 0; i < c; ++i) {
    int *__restrict dummy; // should not influence optimizations !
    struct A a = {i, i, i, i, i, i, i, i};
    tmp = tmp + a.e;
  }
  return tmp;
}



// CHECK-LABEL: define dso_local i32 @test_sroa02a(
// CHECK-SAME: i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP5_NOT:%.*]] = icmp eq i32 [[C]], 0
// CHECK-NEXT:    br i1 [[CMP5_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER:.*]]
// CHECK:       [[FOR_BODY_PREHEADER]]:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[C]], -1
// CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i33
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], -2
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i33
// CHECK-NEXT:    [[TMP4:%.*]] = mul i33 [[TMP1]], [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i33 [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = trunc nuw i33 [[TMP5]] to i32
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[C]], [[TMP6]]
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], -1
// CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[TMP_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP8]], %[[FOR_BODY_PREHEADER]] ]
// CHECK-NEXT:    ret i32 [[TMP_0_LCSSA]]
//
int test_sroa02a(unsigned c) {
  int tmp = 0;
  struct A a;
  for (int i = 0; i < c; ++i) {
    a = constructIt(i);
    tmp = tmp + a.e;
  }
  return tmp;
}



// CHECK-LABEL: define dso_local i32 @test_sroa02b(
// CHECK-SAME: i32 noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp eq i32 [[C]], 0
// CHECK-NEXT:    br i1 [[CMP14_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER:.*]]
// CHECK:       [[FOR_BODY_PREHEADER]]:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[C]], -1
// CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i33
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], -2
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i33
// CHECK-NEXT:    [[TMP4:%.*]] = mul i33 [[TMP1]], [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i33 [[TMP4]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = trunc nuw i33 [[TMP5]] to i32
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[C]], [[TMP6]]
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], -1
// CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[TMP_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP8]], %[[FOR_BODY_PREHEADER]] ]
// CHECK-NEXT:    ret i32 [[TMP_0_LCSSA]]
//
int test_sroa02b(unsigned c) {
  struct A a;
  int tmp = 0;
  for (int i = 0; i < c; ++i) {
    a = (struct A){i, i, i, i, i, i, i, i};
    tmp = tmp + a.e;
  }
  return tmp;
}

//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META4:![0-9]+]], i64 0}
// CHECK: [[META3]] = !{!"A", [[META4]], i64 0, [[META4]], i64 4, [[META4]], i64 8, [[META4]], i64 12, [[META4]], i64 16, [[META4]], i64 20, [[META4]], i64 24, [[META4]], i64 28}
// CHECK: [[META4]] = !{!"int", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// CHECK: [[META6]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[TBAA7]] = !{[[META3]], [[META4]], i64 4}
// CHECK: [[TBAA8]] = !{[[META3]], [[META4]], i64 8}
// CHECK: [[TBAA9]] = !{[[META3]], [[META4]], i64 12}
// CHECK: [[TBAA10]] = !{[[META3]], [[META4]], i64 16}
// CHECK: [[TBAA11]] = !{[[META3]], [[META4]], i64 20}
// CHECK: [[TBAA12]] = !{[[META3]], [[META4]], i64 24}
// CHECK: [[TBAA13]] = !{[[META3]], [[META4]], i64 28}
//.
